openapi: "3.0.0"
servers:
  - url: "http://localhost:9087"
info:
  version: 1.0.0
  title: Minimal ping API server
paths:
  /unlock:
    get:
      responses:
        '200':
          description: unlock success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonData'

  /ping:
    get:
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
components:
  schemas:
    # base types
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
    CommonData:
      type: object
      required:
        - code
        - desc
      properties:
        code:
          type: string
          example: OK
        desc:
          type: string
          example: SUCCESS
